# Generated by Django 2.0.2 on 2018-03-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('post_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('post_code_structured', models.CharField(max_length=15)),
                ('SFBB_avail', models.FloatField(null=True)),
                ('UFBB_avail', models.FloatField(null=True)),
                ('NGA_avail', models.FloatField(null=True)),
                ('perc_prem_not_2Mb', models.FloatField(null=True)),
                ('perc_prem_not_5Mb', models.FloatField(null=True)),
                ('perc_prem_not_10Mb', models.FloatField(null=True)),
                ('perc_prem_not_30Mb', models.FloatField(null=True)),
                ('median_dl_speed', models.FloatField(null=True)),
                ('average_dl_speed', models.FloatField(null=True)),
                ('min_dl_speed', models.FloatField(null=True)),
                ('max_dl_speed', models.FloatField(null=True)),
                ('average_dl_speed_less_10Mb', models.FloatField(null=True)),
                ('average_dl_speed_BBB', models.FloatField(null=True)),
                ('average_dl_speed_SFBB', models.FloatField(null=True)),
                ('average_dl_speed_UTFB', models.FloatField(null=True)),
                ('median_ul_speed', models.FloatField(null=True)),
                ('average_ul_speed', models.FloatField(null=True)),
                ('min_ul_speed', models.FloatField(null=True)),
                ('max_ul_speed', models.FloatField(null=True)),
                ('average_ul_speed_less_10Mb', models.FloatField(null=True)),
                ('average_ul_speed_BBB', models.FloatField(null=True)),
                ('average_ul_speed_SFBB', models.FloatField(null=True)),
                ('average_ul_speed_UFBB', models.FloatField(null=True)),
                ('average_data_usage', models.FloatField(null=True)),
                ('average_data_usage_less_10Mb', models.FloatField(null=True)),
                ('average_data_usage_BBB', models.FloatField(null=True)),
                ('average_data_usage_SFBB', models.FloatField(null=True)),
                ('average_data_usage_UFBB', models.FloatField(null=True)),
                ('post_code_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Checker.Area')),
            ],
        ),
    ]
