# Generated by Django 2.0.2 on 2018-03-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='average_dl_speed_UTFB',
            new_name='average_dl_speed_UFBB',
        ),
    ]
